//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: vtui.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "vtui_wdr.cpp"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "vtui_wdr.h"


// Implement window functions

wxSizer *BuildingDialogFunc( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, "Building Levels", wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxString *strs4 = (wxString*) NULL;
    wxListBox *item4 = new wxListBox( parent, ID_LEVEL, wxDefaultPosition, wxSize(60,100), 0, strs4, wxLB_SINGLE );
    item2->Add( item4, 1, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    wxFlexGridSizer *item5 = new wxFlexGridSizer( 2, 0, 0 );

    wxButton *item6 = new wxButton( parent, ID_LEVEL_COPY, "Copy", wxDefaultPosition, wxSize(40,-1), 0 );
    item6->Enable( FALSE );
    item5->Add( item6, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxTOP, 5 );

    wxButton *item7 = new wxButton( parent, ID_LEVEL_DEL, "Del", wxDefaultPosition, wxSize(40,-1), 0 );
    item7->Enable( FALSE );
    item5->Add( item7, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxTOP, 5 );

    wxButton *item8 = new wxButton( parent, ID_LEVEL_UP, "Up", wxDefaultPosition, wxSize(40,-1), 0 );
    item5->Add( item8, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxButton *item9 = new wxButton( parent, ID_LEVEL_DOWN, "Down", wxDefaultPosition, wxSize(40,-1), 0 );
    item5->Add( item9, 0, wxALIGN_CENTRE|wxALL, 5 );

    item2->Add( item5, 0, wxALIGN_CENTRE|wxALL, 5 );

    item1->Add( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxStaticBox *item11 = new wxStaticBox( parent, -1, "Level Properties" );
    wxStaticBoxSizer *item10 = new wxStaticBoxSizer( item11, wxVERTICAL );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT, "Stories:", wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxSpinCtrl *item14 = new wxSpinCtrl( parent, ID_STORIES, "0", wxDefaultPosition, wxSize(60,-1), 0, 0, 100, 0 );
    item12->Add( item14, 0, wxALIGN_CENTRE|wxALL, 5 );

    item10->Add( item12, 0, wxALIGN_CENTER_VERTICAL, 5 );

    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, "Story Height:", wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxTextCtrl *item17 = new wxTextCtrl( parent, ID_STORY_HEIGHT, "", wxDefaultPosition, wxSize(60,-1), 0 );
    item15->Add( item17, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, "meters", wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item18, 0, wxALIGN_CENTRE|wxRIGHT|wxTOP|wxBOTTOM, 5 );

    item10->Add( item15, 0, wxALIGN_CENTER_VERTICAL, 5 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, "Material:", wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, ID_MATERIAL, "", wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item19->Add( item21, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxButton *item22 = new wxButton( parent, ID_SET_MATERIAL, "Set", wxDefaultPosition, wxSize(40,-1), 0 );
    item19->Add( item22, 0, wxALIGN_CENTRE|wxALL, 5 );

    item10->Add( item19, 0, wxALIGN_CENTER_VERTICAL, 5 );

    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item24 = new wxStaticText( parent, ID_TEXT, "Color:", wxDefaultPosition, wxDefaultSize, 0 );
    item23->Add( item24, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxStaticBitmap *item25 = new wxStaticBitmap( parent, ID_COLOR, vtuiBitmapsFunc( 0 ), wxDefaultPosition, wxSize(32,18) );
    item23->Add( item25, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxButton *item26 = new wxButton( parent, ID_SET_COLOR, "Set", wxDefaultPosition, wxSize(40,-1), 0 );
    item23->Add( item26, 0, wxALIGN_CENTRE|wxALL, 5 );

    item10->Add( item23, 0, wxALIGN_CENTER_VERTICAL, 5 );

    wxBoxSizer *item27 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item28 = new wxStaticText( parent, ID_TEXT, "Edge Slopes:", wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item28, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxTextCtrl *item29 = new wxTextCtrl( parent, ID_EDGE_SLOPES, "", wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item27->Add( item29, 0, wxALIGN_CENTRE|wxRIGHT|wxTOP|wxBOTTOM, 5 );

    wxButton *item30 = new wxButton( parent, ID_SET_EDGE_SLOPES, "Set", wxDefaultPosition, wxSize(40,-1), 0 );
    item27->Add( item30, 0, wxALIGN_CENTRE|wxALL, 5 );

    item10->Add( item27, 0, wxALIGN_CENTRE, 5 );

    item1->Add( item10, 0, wxALIGN_CENTRE|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxBoxSizer *item31 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item32 = new wxButton( parent, wxID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 );
    item31->Add( item32, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxButton *item33 = new wxButton( parent, wxID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 );
    item31->Add( item33, 0, wxALIGN_CENTRE|wxALL, 5 );

    item0->Add( item31, 0, wxALIGN_CENTRE|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

// Implement menubar functions

// Implement toolbar functions

// Implement bitmap functions

wxBitmap vtuiBitmapsFunc( size_t index )
{
    if (index == 0)
    {
        /* XPM */
        static const char *xpm_data[] = {
        /* columns rows colors chars-per-pixel */
        "32 18 5 1",
        "a c Black",
        "b c #FF0000",
        "c c #00FF00",
        "d c #0000FF",
        "e c #FFFFFF",
        /* pixels */
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaeaaaaaaeaaaaaaaaeaaeaaaaaaaa",
        "aaaaeaaaaaeaaaaaaaaaeaaeaaaaaaaa",
        "aaaaeaaaaaeaaaaaaaaaeaaeaaaaaaaa",
        "aaaaeaaaeeeeaaaaaaaaeaeeeaaaaaaa",
        "aaaaeaaaaaeaaaaaaaaaeaaeaaaaaaaa",
        "aaaeeaaeeaeaaeeaeaeaeaaeaaaaeaaa",
        "aaeaeaeaeaeaeaeaeaeaeaaeaaaeeeaa",
        "aaeaeaeaeaeaeaeaeaeaeaaeaaeeeeea",
        "aaeaeaeeaaeaeaeaeaeaeaaeaaaeeeaa",
        "aaeaeaeaaaeaeaeaeaeaeaaeaaaaeaaa",
        "aaaeeaaeeaeaaeaeaeaaeaaeaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "aabbbbbbbbaaccccccccaadddddddaaa",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        };
        wxBitmap bitmap( xpm_data );
        return bitmap;
    }
    return wxNullBitmap;
}


// End of generated file
