#ifndef __DriveDlg__
#define __DriveDlg__

/**
@file
Subclass of DriveDlgBase, which is generated by wxFormBuilder.
*/

#include "EnviroUI.h"
#include "..//CarEngine.h"

//// end generated include

/** Implementing DriveDlgBase */
class DriveDlg : public DriveDlgBase
{
protected:
	// Handlers for DriveDlgBase events.
	void m_areaOnLeftDown( wxMouseEvent& event );
	void m_areaOnLeftUp( wxMouseEvent& event );
	void m_areaOnMotion( wxMouseEvent& event );

public:
	/** Constructor */
	DriveDlg( wxWindow* parent );
//// end generated class members

	void SetCarEngine(CarEngine *eng) { m_Engine = eng; }
	CarEngine *GetCarEngine() { return m_Engine.get(); }

protected:
	CarEnginePtr m_Engine;
};

#endif // __DriveDlg__
