
// ID for the menu commands
enum
{
	ID_FILE_LAYERS = 1,

	ID_TOOLS_SELECT,
	ID_TOOLS_FENCES,
	ID_TOOLS_ROUTES,
	ID_TOOLS_PLANTS,
	ID_TOOLS_INSTANCES,
	ID_TOOLS_MOVE,
	ID_TOOLS_NAVIGATE,
	ID_TOOLS_MEASURE,

	ID_VIEW_MAINTAIN,
	ID_VIEW_WIREFRAME,
	ID_VIEW_FULLSCREEN,
	ID_VIEW_TOPDOWN,
	ID_VIEW_FRAMERATE,
	ID_VIEW_SLOWER,
	ID_VIEW_FASTER,
	ID_VIEW_SETTINGS,
	ID_VIEW_FOLLOW_ROUTE,
	ID_VIEW_LOCATIONS,
	ID_VIEW_SNAPSHOT,
	ID_VIEW_SNAP_AGAIN,

	ID_NAV_NORMAL,
	ID_NAV_VELO,
	ID_NAV_GRAB_PIVOT,
	ID_NAV_QUAKE,
	ID_NAV_PANO,

	ID_SCENE_SCENEGRAPH,
	ID_SCENE_TERRAIN,
	ID_SCENE_SPACE,
	ID_SCENE_SAVE,

	ID_TIME_STOP,
	ID_TIME_FASTER,

	ID_TERRAIN_DYNAMIC,
	ID_TERRAIN_CULLEVERY,
	ID_TERRAIN_CULLONCE,
	ID_TERRAIN_SKY,
	ID_TERRAIN_OCEAN,
	ID_TERRAIN_PLANTS,
	ID_TERRAIN_STRUCTURES,
	ID_TERRAIN_ROADS,
	ID_TERRAIN_FOG,
	ID_TERRAIN_INCREASE,
	ID_TERRAIN_DECREASE,
	ID_TERRAIN_SAVEVEG,
	ID_TERRAIN_SAVESTRUCT,
	ID_TERRAIN_FOUNDATIONS,

	ID_EARTH_SHOWSHADING,
	ID_EARTH_SHOWAXES,
	ID_EARTH_TILT,
	ID_EARTH_FLATTEN,
	ID_EARTH_UNFOLD,
	ID_EARTH_POINTS,

	ID_HELP_ABOUT,

	// popup
	ID_POPUP_PROPERTIES,
	ID_POPUP_FLIP,
	ID_POPUP_RELOAD,
	ID_POPUP_DELETE
};
