
// ID for the menu commands
enum
{
	ID_TOOLS_SELECT = 1,
	ID_TOOLS_FENCES,
	ID_TOOLS_ROUTES,
	ID_TOOLS_TREES,
	ID_TOOLS_MOVE,
	ID_TOOLS_NAVIGATE,

	ID_VIEW_MAINTAIN,
	ID_VIEW_GRAB_PIVOT,
	ID_VIEW_WIREFRAME,
	ID_VIEW_FULLSCREEN,
	ID_VIEW_TOPDOWN,
	ID_VIEW_FRAMERATE,
	ID_VIEW_SLOWER,
	ID_VIEW_FASTER,
	ID_VIEW_SETTINGS,
	ID_VIEW_FOLLOW_ROUTE,
	ID_VIEW_LOCATIONS,

	ID_SCENE_SCENEGRAPH,
	ID_SCENE_TERRAIN,
	ID_SCENE_SPACE,
	ID_SCENE_SAVE,

	ID_TERRAIN_REGULAR,
	ID_TERRAIN_DYNAMIC,
	ID_TERRAIN_CULLEVERY,
	ID_TERRAIN_CULLONCE,
	ID_TERRAIN_SKY,
	ID_TERRAIN_OCEAN,
	ID_TERRAIN_TREES,
	ID_TERRAIN_ROADS,
	ID_TERRAIN_FOG,
	ID_TERRAIN_INCREASE,
	ID_TERRAIN_DECREASE,
	ID_TERRAIN_SAVEVEG,
	ID_TERRAIN_SAVESTRUCT,

	ID_EARTH_SHOWTIME,
	ID_EARTH_FLATTEN,
	ID_EARTH_POINTS,
	ID_EARTH_LINEAR,

	ID_HELP_ABOUT,

	// popup
	ID_POPUP_PROPERTIES,
	ID_POPUP_DELETE
};
