//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Enviro.rc
//
#define IDC_OPENGL_INFO                 3
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 102
#define CG_IDS_PROGRESS_CAPTION         103
#define CG_IDS_PROGRESS_CAPTION2        104
#define IDR_MAINFRAME                   128
#define IDR_ENVIROTYPE                  129
#define IDD_TPARAMS                     130
#define IDD_STATDLG                     131
#define IDD_STARTUP                     132
#define IDD_TERRAIN                     133
#define IDD_PLANTDLG                    134
#define IDD_FENCEDLG                    135
#define IDC_VERTEXAG                    1001
#define IDC_FILENAME                    1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_TILESIZE                    1004
#define IDC_TFILENAME                   1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_MIPMAP                      1006
#define IDC_TFILEBASE                   1007
#define IDC_16BIT                       1008
#define IDC_PLANTS                      1009
#define IDC_FSPEED1                     1010
#define IDC_PRELIGHT                    1010
#define IDC_ROADS                       1011
#define IDC_SKY                         1012
#define IDC_FENCES                      1013
#define IDC_TFILEBASE2                  1013
#define IDC_NONE                        1014
#define IDC_SINGLE                      1015
#define IDC_TILED                       1016
#define IDC_DERIVED                     1017
#define IDC_TEXROADS                    1018
#define IDC_FOG                         1019
#define IDC_WIDTHEXAG                   1020
#define IDC_ROADHEIGHT                  1020
#define IDC_TFILESINGLE                 1021
#define IDC_VEGDISTANCE                 1022
#define IDC_SIZEEXAG                    1023
#define IDC_TIMEOFDAY                   1024
#define IDC_INITTIME                    1025
#define IDC_DYNAMIC                     1028
#define IDC_FOGDISTANCE                 1029
#define IDC_MOTIONSCRIPT                1030
#define IDC_VERTEXCOLORS                1031
#define IDC_OVERLAY                     1033
#define IDC_OCEANPLANE                  1034
#define IDC_EDIT1                       1035
#define IDC_HWY                         1035
#define IDC_SHADOWS                     1036
#define IDC_BILLBOARDS                  1037
#define IDC_LABELS                      1038
#define IDC_MINHEIGHT                   1039
#define IDC_PAVED                       1040
#define IDC_DIRT                        1041
#define IDC_PRELIT                      1042
#define IDC_TREEFILE                    1043
#define IDC_ROADFILE                    1044
#define IDC_BUILDINGFILE                1046
#define IDC_BUILDINGS                   1047
#define IDC_VEHICLES                    1048
#define IDC_WILDVEG                     1049
#define IDC_AGRI                        1050
#define IDC_VEHICLESIZE                 1051
#define IDC_FENCEFILE                   1052
#define IDC_MAXTEXSIZE                  1053
#define IDC_AIRPORTS                    1053
#define IDC_TRISTRIPS                   1055
#define IDC_DETAILTEXTURE               1056
#define IDC_ROADDISTANCE                1057
#define IDC_DOSCRIPT                    1058
#define IDC_NAVSPEED                    1060
#define IDC_LIGHT_FACTOR                1061
#define IDC_CARNUMBER                   1064
#define IDC_CHECK1                      1065
#define IDC_ROADCULTURE                 1065
#define IDC_CHECK2                      1066
#define IDC_CHECK3                      1067
#define IDC_CHECK4                      1068
#define IDC_BUTTON1                     1069
#define IDC_TSELECT                     1069
#define IDC_NEW                         1069
#define IDC_BUTTON2                     1070
#define IDC_LODMETHOD                   1070
#define IDC_DELETE                      1070
#define IDC_PICKPATH                    1070
#define IDC_EDITPROP                    1070
#define IDC_BUTTON3                     1071
#define IDC_EDIT                        1071
#define IDC_BUTTON4                     1072
#define IDC_VEHICLESPEED                1073
#define IDC_FULLSCREEN                  1073
#define IDC_TOOLBAR                     1074
#define IDC_HTMLPANE                    1075
#define IDC_LAUNCH1                     1076
#define IDC_LAUNCH2                     1077
#define IDC_TNAME                       1078
#define IDC_TLIST                       1079
#define IDC_STATICDATE                  1080
#define IDC_PLANTSIZE                   1081
#define IDC_DATAPATH                    1082
#define IDC_STATICIMAGE                 1083
#define IDC_IMAGE                       1084
#define IDC_SPECIES                     1085
#define IDC_SIZESLIDER                  1087
#define IDC_SIZEEDIT                    1088
#define IDC_SPACINGEDIT                 1089
#define IDC_FENCETYPE                   1090
#define IDC_SPACINGSLIDER               1091
#define IDC_HEIGHTSLIDER                1092
#define IDC_HEIGHTEDIT                  1093
#define IDD_TREEVIEW                    20101
#define IDD_CAMDIALOG                   20102
#define IDD_KEYDIALOG                   20103
#define IDD_ORIENT                      20104
#define IDD_ENVIRON                     20105
#define IDD_REMOTEDIALOG                20106
#define IDC_TREE1                       21000
#define IDC_HITHER_S                    21001
#define IDC_YON_S                       21002
#define IDC_HITHER                      21003
#define IDC_YON                         21004
#define IDC_VANGLE_S                    21005
#define IDC_VANGLE                      21006
#define IDC_ZOOMTOSCENE                 21007
#define IDC_FSPEED                      21008
#define IDC_ZOOMTONODE                  21009
#define IDC_ENABLED                     21011
#define IDC_KPOINTS                     21013
#define IDC_KVISIBLE                    21014
#define IDC_KTYPE                       21015
#define IDC_ASPECT                      21016
#define IDC_PLAYCAM                     21017
#define IDC_VPLIST                      21018
#define IDC_BUTTON_STORE1               21020
#define IDC_BUTTON_STORE2               21021
#define IDC_BUTTON_STORE3               21022
#define IDC_BUTTON_STORE4               21023
#define IDC_BUTTON_STORE5               21024
#define IDC_BUTTON_STORE6               21025
#define IDC_BUTTON_RECALL1              21026
#define IDC_BUTTON_RECALL2              21027
#define IDC_BUTTON_RECALL3              21028
#define IDC_BUTTON_RECALL4              21029
#define IDC_BUTTON_RECALL5              21030
#define IDC_BUTTON_RECALL6              21031
#define IDC_FSPEED_S                    21040
#define IDC_PITCH                       21041
#define IDC_YAW                         21042
#define IDC_PLAYANIM                    21043
#define IDC_START2                      21201
#define IDC_START1                      21202
#define IDC_END2                        21203
#define IDC_END1                        21204
#define IDC_FOGCOLOR                    21206
#define IDC_BGCOLOR                     21207
#define IDC_LINEAR                      21208
#define IDC_EXPONENTIAL                 21209
#define IDC_EXPONENTIAL2                21210
#define IDC_DENSITY1                    21211
#define IDC_DENSITY2                    21212
#define IDC_REMOTEFILE                  21213
#define IDC_AMBIENT                     21214
#define ID_VIEW_SCENEGRAPH              21372
#define ID_VIEW_FULLSCREEN              21373
#define ID_VIEW_DISABLELIGHTING         21374
#define ID_TEST_SHOWINFO                21375
#define ID_VIEW_ZOOMALL                 21376
#define ID_VIEW_FRAMERATECOUNTER        21387
#define ID_TEST_CAMDIALOG               21392
#define ID_VIEW_WIREFRAME               21393
#define ID_VIEW_ENVIRON                 21394
#define ID_SCPT_SAVE                    21400
#define ID_SCPT_OPEN                    21402
#define ID_SCPT_RECORD                  21403
#define ID_SCPT_STOP                    21404
#define ID_SCPT_RUN                     21405
#define ID_SCPT_STOPRUN                 21406
#define ID_SCPT_REPLAY                  21407
#define ID_SCPT_FASTER                  21408
#define ID_SCPT_SLOWER                  21409
#define ID_OPEN_REMOTE_FILE             21410
#define ID_VIEW_SKIN                    21411
#define ID_ENVIRO_TIMEON                32771
#define ID_ENVIRO_REGULARTERRAIN        32774
#define ID_ENVIRO_LODTERRAIN            32777
#define ID_ENVIRO_CULLEVERYFRAME        32778
#define ID_ENVIRO_CULLONCE              32779
#define ID_ENVIRO_DRIVEROADS            32780
#define ID_ENVIRO_INCREASE              32781
#define ID_ENVIRO_DECREASE              32783
#define ID_ENVIRO_SHOWROADS             32784
#define ID_ENVIRO_SHOWSKY               32785
#define ID_ENVIRO_SHOWOCEAN             32786
#define ID_VIEW_SPINTHEMAINLIGHT        32788
#define ID_ENVIRO_SHOWTREES             32789
#define ID_ENVIRO_SHOWFOG               32790
#define ID_ENVIRO_SHOWDETAILTEXTURE     32794
#define ID_TOOLS_FENCES                 32795
#define ID_TOOLS_TREES                  32796
#define ID_TOOLS_NAVIGATE               32797
#define ID_TOOLS_SELECT                 32798
#define ID_VIEW_FLYFASTER               32802
#define ID_VIEW_FLYSLOWER               32803
#define ID_VIEW_MAINTAINHEIGHT          32804
#define ID_VIEW_TOPDOWN                 32805
#define ID_TOOLS_NAVIGATE_ORIGINALNAVENGIN 32812
#define ID_TOOLS_NAVIGATE_QUAKENAVENGINE 32813
#define ID_TOOLS_NAVIGATE_VELOCITYGRAVITY 32816
#define ID_FLYTO_SPACE                  32817
#define ID_FLYTO_TERRAIN                32818
#define ID_SPACE_SHOWTIME               32821
#define ID_EARTH_SHOWSHADING            32821
#define ID_EARTH_FLATUNFOLD             32822
#define ID_EARTH_ADDPOINTDATA           32823
#define ID_TOOLS_MOVE                   32825

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
